### ISSUE TITLE
Mapped reads code looks like it's in the wrong place

### ISSUE THREAD

**Issue by anderspitman** [iobio/iobio-charts#134]
The mapped reads data is based on the read depth data. Therefore, we want `mapped-reads-from-index-file` to be emitted when the read depth data is parsed from the index file. I think we want it after this: https://github.com/iobio/iobio-charts/blob/850b5651d19eca34ba9199351cc94c78e1870bb1/data_broker.js#L206

**Comment by YangQi007** [comment]
The code you mentioned above is in the block ` if (alignmentUrlChanged)  `. If we emit the `mapped-reads-from-index-file `after the code you mentioned, the event will not be emitted if the aligmenURL is the same. But we want to update the mapped reads chart even if the "alignmentURL" is the same. 

I put mapped reads data in the `_updateStats()` because the mapped reads chart will be updated when the user click the `All`or `single` chromosome.

**Comment by anderspitman** [comment]
Ah I see my mistake. `mappedReads` is not only based off the read depth data, it's also based off the currently selected regions.
