### ISSUE TITLE
Add loading indicators to percent and histogram charts

### ISSUE THREAD

**Issue by anderspitman** [iobio/iobio-charts#24]

**Comment by YangQi007** [comment]
The percent box charts are loaded faster than any other charts because of the default data when loading in the beginning. If we are going to show the default pie chart based on the data = [1, 1], would the loading indicator be needed there?

 If we are going to have the same loading effect as the bam1, we can change the default data = [] and return nothing if the data's length is 0 in the pie.js. Is that ok to change the code in iobio.viz repo? Please see the code snippet below. 

![Image](https://github.com/user-attachments/assets/723a97a7-6647-4f74-ae96-ad1397cbb609)
